using System.Collections.Generic;

namespace JASON_Compiler
{
    public static class JASON_Compiler
    {
        // Phase 1 lexical analyzer
        public static Scanner Jason_Scanner = new Scanner();

        // Final token stream generated by the scanner
        public static List<Token> TokenStream = new List<Token>();

        public static void Start_Compiling(string sourceCode)
        {
            // Run Phase 1: Lexical Analysis
            Jason_Scanner.StartScanning(sourceCode);

            // Store the scanner output
            TokenStream = Jason_Scanner.Tokens;
        }
    }
}